### ISSUE TITLE
broken link https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev921_linux_x86-64.tar.gz

### ISSUE THREAD

**Issue by PasaOpasen** [uplinktv/ibmmq-devops#1]
There is not file https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev921_linux_x86-64.tar.gz

**Comment by mattrpav** [comment]
@PasaOpasen IBM updates the version from time to time. You can browse the root folder to find the latest.

In this case it is: [mqadv_dev932_linux_x86-64.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev932_linux_x86-64.tar.gz)

**Comment by PasaOpasen** [comment]
@mattrpav I understand, but there is no any linux_x86-64 archive, only windows

**Comment by mattrpav** [comment]
When I browse: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/

I see a lot of linux versions to download. If you are not able to see them, perhaps IBM is not permitting downloads from your location?

<img width="786" alt="Screenshot 2023-11-09 at 8 35 00 AM" src="https://github.com/uplinktv/ibmmq-devops/assets/512119/49858b92-d55a-4f6e-9208-965b4708f914">

**Comment by PasaOpasen** [comment]
![изображение](https://github.com/uplinktv/ibmmq-devops/assets/45700689/5e55cf79-3ffa-4986-a564-478c3da1ff49)
interesting

**Comment by PasaOpasen** [comment]
Okay, seems like it is a country restriction
